version: "3.8"
services:
    Discovery-Server:
        image: discovery-server:latest
        # build: ./Discovery-Server
        container_name: discovery-server
        ports: 
          - "8900:8900"
    TicketGateway:
        image: ticket-gateway:latest
        # build: ./TicketGateway
        container_name: ticket-gateway
        ports:
          - "8899:8899"
          # -target: 8899
          #  published: 8899
        depends_on:
          - "Discovery-Server"
    CreateTicketService:
        # build: ./create
        image: createticketservice:latest
        container_name: create-ticket-api
        ports: 
          - "8901:8901"
          # - target: 8901
          #   published: 8901
        depends_on:
          - "Discovery-Server"
    ReadTicketService:
        # build: ./read
        image: readticketservice:latest
        container_name: read-ticket-api
        ports: 
          - "8904:8904"
          # - target: 8904
          #   published: 8904
        depends_on:
          - "Discovery-Server"
    ReadAllTicketService:
        # build: ./readAll
        image: readallticketservice:latest
        container_name: read-all-tickets-api
        ports: 
          - "8903:8903"
          # - target: 8903
          #   published: 8903
        depends_on:
          - "Discovery-Server"
    UpdateTicketService:
        # build: ./Update
        image: updateticketservice:latest
        container_name: update-ticket-api
        ports: 
          - "8905:8905"
          # - target: 8905
          #   published: 8905
        depends_on:
          - "Discovery-Server"
    DeleteTicketService:
        # build: ./Delete
        image: deleteticketservice:latest
        container_name: delete-ticket-api
        ports:
          - "8902:8902" 
          # - target: 8902
          #   published: 8902
        depends_on:
          - "Discovery-Server"
    frontend:
        container_name: frontend
        # build: ./Frontend
        image: frontend:latest
        ports:
          - "3000:3000"
        # - target: 3000
        #   published: 3000
          # protocol: tcp