apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: projectapp
data:
  default.conf:
    server {
        listen 80;
        location / {
            proxy_pass http://frontendapp:3000;
        }
    }