apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: projectapp
data:
  default.conf:
    server {
        listen 80;
        location / {
            proxy_pass http://frontendapp:3000;
        }
        location /gateway {
            proxy_pass http://backend-gateway:8899;
        }
        # location /eureka {
        #     proxy_pass http://backend-disco:8900;
        # }
    }