apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-disco
  namespace: projectapp
  labels: 
    app: backend-disco
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-disco
  template:
    metadata:
      labels:
        app: backend-disco
    spec:
      containers:
      - name: discovery-server
        image: lukef2021/discovery-server:latest
        imagePullPolicy: Always
        imagePullSecrets:
          - name: cred
        ports:
        - containerPort: 8900
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-create
  namespace: projectapp
  labels: 
    app: backend-create
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-create
  template:
    metadata:
      labels:
        app: backend-create
    spec:
      containers:
      - name: create-ticket-api
      # env: 
        #   - name: eureka-server-port
        #     value: http://backend-disco:8900/eureka/
        image: lukef2021/createticketservice:latest
        imagePullPolicy: Always
        imagePullSecrets:
          - name: cred
        ports:
        - containerPort: 8901
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-read
  namespace: projectapp
  labels: 
    app: backend-read
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-read
  template:
    metadata:
      labels:
        app: backend-read
    spec:
      containers:
      - name: read-ticket-api
        image: lukef2021/readticketservice:latest
        imagePullPolicy: Always
        imagePullSecrets:
          - name: cred
        ports:
        - containerPort: 8904
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-read-all
  namespace: projectapp
  labels: 
    app: backend-read-all
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-read-all
  template:
    metadata:
      labels:
        app: backend-read-all
    spec:
      containers:
      - name: read-all-tickets-api
        image: lukef2021/readallticketservice:latest
        imagePullPolicy: Always
        imagePullSecrets:
          - name: cred
        ports:
        - containerPort: 8903
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-update
  namespace: projectapp
  labels: 
    app: backend-update
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-update
  template:
    metadata:
      labels:
        app: backend-update
    spec:
      containers:
      - name: update-ticket-api
        image: lukef2021/updateticketservice:latest
        imagePullPolicy: Always
        imagePullSecrets:
          - name: cred
        ports:
        - containerPort: 8905
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-delete
  namespace: projectapp
  labels: 
    app: backend-delete
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-delete
  template:
    metadata:
      labels:
        app: backend-delete
    spec:
      containers:
      - name: delete-ticket-api
        image: lukef2021/deleteticketservice:latest
        imagePullPolicy: Always
        imagePullSecrets:
          - name: cred
        ports:
        - containerPort: 8902
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-gateway
  namespace: projectapp
  labels: 
    app: backend-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-gateway
  template:
    metadata:
      labels:
        app: backend-gateway
    spec:
      containers:
      - name: ticket-gateway
        image: lukef2021/ticket-gateway:latest
        imagePullPolicy: Always
        imagePullSecrets:
          - name: cred
        ports:
        - containerPort: 8899

