# apiVersion: v1
# kind: Pod
# metadata:
#   name: frontendapp
#   namespace: projectapp
#   labels:
#     app: frontendapp
# spec:
#   containers:
#   - name: frontendapp
#     image: lukef2021/frontend
#     imagePullPolicy: Always
#     ports:
#     - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontendapp
  namespace: projectapp
  labels:
    app: frontendapp
spec:
  selector:
    app: frontendapp
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP