apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendapp
  namespace: projectapp
  labels: 
    app: frontendapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontendapp
  template:
    metadata:
      labels:
        app: frontendapp
    spec:
      containers:
      - name: frontendapp
        image: lukef2021/frontend:latest
        imagePullPolicy: Always
      imagePullSecrets:
        - name: cred
        ports:
        - containerPort: 3000